// Autogenerated by infra_lib 0.0.1 on 2025-09-22T12:41:56+00:00 UTC.

namespace IaC_example
{
    class LocalRunner
    {
        static async Task Main()
        {

            if (EnvironmentSettings.Instance.IsDebugging)
            {
                await LocalLambdaProxy.RunLocalProxy(async (request) =>
                {
                    var lambda = new LambdaApp();
                    return await lambda.HandlerAsync(request);
                },
                routePrefix: "test",
                port: 5000);
                return;
            }

        }

    }
}