# Autogenerated by infra_lib 0.0.1 on 2025-09-22T12:41:56+00:00 UTC.

import os
from infra_lib import InfraEnvironment, AWSInfraBuilder, AWSQueueConfig, AWSLambdaParameters

class LocalInfra(AWSInfraBuilder):
    def build(self):
        """
        Build the infrastructure for local environment and net8_lambda stack.
        """
        # Create secrets first
        self.secrets_util.create_secrets()
        
        ## Add more infra