services:
  localstack:
    profiles: ["local", "stage"]
    image: localstack/localstack:4.7.0
    container_name: localstack
    ports:
      - "4566:4566"  # AWS services endpoint
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sqs,events,secretsmanager,cloudformation,apigateway,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  lambda-debug:
    profiles: ["local"]
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile.debug
    container_name: lambda-debug 
    ports:
      - "5005:5005"  # Debugger attach port for VSCode
      - "5000:5000"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - IAC_ENVIRONMENT=${IAC_ENVIRONMENT}
      - LOCALSTACK_URL=${LOCALSTACK_URL}
      - LOCALSTACK_SECRETS_MANAGER_URL=${LOCALSTACK_SECRETS_MANAGER_URL}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - localstack